package com.example.cflat.compiler.lexer;

public enum TokenType {
    KW_INT, KW_CHAR, KW_BOOL, KW_VOID,
    KW_IF, KW_ELSE, KW_WHILE, KW_FOR,
    KW_BREAK, KW_CONTINUE, KW_RETURN,
    KW_TRUE, KW_FALSE, KW_PRINTF, KW_SCANF,
    IDENTIFIER, INT_LITERAL, CHAR_LITERAL, STRING_LITERAL,
    PLUS, MINUS, STAR, SLASH, PERCENT,
    PLUSPLUS, MINUSMINUS,
    PLUSEQ, MINUSEQ, STAREQ, SLASHEQ, PERCENTEQ,
    LT, LTE, GT, GTE, EQEQ, NEQ,
    ANDAND, OROR, BANG, ASSIGN,
    LPAREN, RPAREN, LBRACE, RBRACE, LBRACKET, RBRACKET,
    SEMICOLON, COMMA,
    EOF
}
